version: "3.9"

services:
  web:
    build: .
    restart: always
    networks:
      - currency-network
    container_name: backend-currency
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.3-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - currency-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  currency-network:
volumes:
  pg_data: